### ISSUE TITLE
Rebuild using mailchimp-api-v3

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-mailchimp-source#4]
Since being initially developed, Mailchimp has released version 3 of their API. This integration should be rebuilt to take advantage of these new features, using the pre-built node package below:
https://www.npmjs.com/package/mailchimp-api-v3

Requirements
- Support pagination
   - Each request accepts `offset` and `count` request parameter and returns a `total_items` value. These two should be used to support [pagination](https://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/) in the total request.
- Create methods corresponding endpoints:
   - [`/campaigns`](http://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/#read-get_campaigns)
   - [`/conversations`](http://developer.mailchimp.com/documentation/mailchimp/reference/conversations/#read-get_conversations)
   - [`/ecommerce/stores`](http://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/#read-get_ecommerce_stores)
   - [`/file-manager/files`](http://developer.mailchimp.com/documentation/mailchimp/reference/file-manager/files/#read-get_file_manager_files)
   - [`/file-manager/folders`](http://developer.mailchimp.com/documentation/mailchimp/reference/file-manager/folders/#read-get_file_manager_folders)
   - [`/lists`](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/#read-get_lists)
   - [`/reports`](http://developer.mailchimp.com/documentation/mailchimp/reference/reports/#read-get_reports)
   - [`/templates`](http://developer.mailchimp.com/documentation/mailchimp/reference/templates/#read-get_templates)
   - [`/template-folders`](http://developer.mailchimp.com/documentation/mailchimp/reference/template-folders/)
- Allow all native parameters to be added into the config, including the following (and all additional parameters by method)
   - `fields`
   - `exclude_fields`
   - `count`
   - `offset`
   - `type`
   - `status`
   - `before_send_time`
   - `since_send_time`
   - `before_create_time`
   - `since_create_time`

**Comment by ryw** [comment]
no more work on aries
